# Generated by Django 5.0.3 on 2024-05-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='banquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rent', models.BigIntegerField()),
                ('address', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
