# Generated by Django 5.0.6 on 2024-05-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquet',
            name='bimage1',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banquet',
            name='bimage2',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banquet',
            name='bimage3',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
