# Generated by Django 5.0.6 on 2024-05-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0007_morder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='mid',
        ),
        migrations.AddField(
            model_name='rating',
            name='bid',
            field=models.ForeignKey(db_column='bid', default=1, on_delete=django.db.models.deletion.CASCADE, to='BBAECAPP.banquet'),
            preserve_default=False,
        ),
    ]
