# Generated by Django 5.0.6 on 2024-05-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0008_remove_rating_mid_rating_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='bid',
        ),
        migrations.AddField(
            model_name='banquet',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
