# Generated by Django 5.0.6 on 2024-05-15 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0009_remove_rating_bid_banquet_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.BigIntegerField()),
                ('banqid', models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='BBAECAPP.banquet')),
            ],
        ),
    ]
