# Generated by Django 5.0.6 on 2024-05-15 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0011_manager_is_active_rating_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='banqid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='BBAECAPP.banquet'),
        ),
    ]
