# Generated by Django 5.0.6 on 2024-05-16 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0012_alter_manager_banqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucart',
            name='bid',
            field=models.ForeignKey(db_column='bid', default=1, on_delete=django.db.models.deletion.CASCADE, to='BBAECAPP.banquet'),
            preserve_default=False,
        ),
    ]
