# Generated by Django 5.0.6 on 2024-05-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0013_menucart_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucart',
            name='bid',
        ),
    ]
