# Generated by Django 5.0.6 on 2024-05-16 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0015_alter_order_bid_alter_order_mid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bid',
            field=models.ForeignKey(db_column='bid', default=100, on_delete=django.db.models.deletion.CASCADE, to='BBAECAPP.banquet'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mid',
            field=models.ForeignKey(db_column='mid', default=100, on_delete=django.db.models.deletion.CASCADE, to='BBAECAPP.menu'),
        ),
    ]
