# Generated by Django 5.0.6 on 2024-05-16 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0017_alter_order_bid_alter_order_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='morder',
            name='bid',
            field=models.ForeignKey(db_column='bid', default=1, on_delete=django.db.models.deletion.CASCADE, to='BBAECAPP.banquet'),
            preserve_default=False,
        ),
    ]
