# Generated by Django 5.0.4 on 2024-04-25 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0004_dishes_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='mid',
            field=models.ForeignKey(db_column='mid', on_delete=django.db.models.deletion.CASCADE, to='BBAECAPP.menu'),
        ),
    ]
