# Generated by Django 5.0.4 on 2024-04-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0005_dishes_is_active_menu_is_active_alter_dishes_mid'),
    ]

    operations = [
        migrations.CreateModel(
            name='banquetmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='banquet',
            name='bimage',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
