# Generated by Django 5.0.4 on 2024-04-29 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0009_menucart'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucart',
            name='banqid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BBAECAPP.banquet', verbose_name='Banquet'),
            preserve_default=False,
        ),
    ]
