# Generated by Django 5.0.4 on 2024-05-06 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0011_alter_menucart_menuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucart',
            name='banqid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBAECAPP.banquet'),
        ),
        migrations.AlterField(
            model_name='menucart',
            name='menuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBAECAPP.menu'),
        ),
        migrations.AlterField(
            model_name='menucart',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
