# Generated by Django 5.0.4 on 2024-05-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0012_alter_menucart_banqid_alter_menucart_menuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
