# Generated by Django 5.0.4 on 2024-05-07 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0014_remove_menucart_menuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='foodcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('banqid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBAECAPP.banquet')),
                ('menuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BBAECAPP.menu')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
