# Generated by Django 5.0.4 on 2024-05-07 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBAECAPP', '0015_foodcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcart',
            name='banqid',
        ),
    ]
